name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "368ec36ce9fe63810e9a39e97d68a4140bc8188149ef56368053fef2383ec3e7"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
