name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc588ec376483769a1c73ff0ec7ed7226fb6c1b8ae13498d248e9a1c55f46b43"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
