name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88492d9299e1612f857c75e613940a1dc0161980b9cd4f234ef28f144fe5fa55"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
