name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb600901ff0747a722c545be65cb4a76d20bbddf44fa4323da83a1efd91ff451"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
