name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "736b013cea249ade7f4f0acc71980100eb2af1b4ca77fd5d2ae3b8f7695613ff"

[versions]
fabric = "0.14.15"
minecraft = "1.19.3"
