name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3426936d7f380b6767034d5fd4ad9505436456f9c53f427949d1af82f6a7d6ba"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
