name = "Cool People Only!"
author = "gabehxd"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4cda5e531303305a6b35295f8a943194aa6a8baad2a366c047781f78a7277d5"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
