name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6035cef11ea8639266999e25fab9a0d55841b8dd50d960324f9228e54df32d67"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
