name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37246e03b792c4a196c6e96f0061b0b414cb740e8f62961d685d01a9cc0f9698"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
