name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee26451a29fec44234b777f3f286a408973676bfbe834799666907c64705ad88"

[versions]
fabric = "0.14.15"
minecraft = "1.19.3"
