name = "Enhancements for Cool People Only!"
author = "gabehxd"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45afb07e0e986a111adfaa1fd2c6fe570b50588af3c91737be0d74e18f73efcf"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
