name = "Cool People Only! Modpack"
author = "gabeh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9d7eb44102397742374edb25007e6fcb420f2525bf2a4abc014750fac99226"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
