name = "Cool People Only! Modpack"
author = "gabeh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54e5279efcb09c616ffdd68e0c476130fe9571c3adf7559c80a83c8cfe5015fb"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
