name = "Cool People Only"
author = "gabeh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e43785a5d2c385033ea6fae06fd3b669474aaeeb18c9d4a8e4c0641602912365"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
