name = "Cool People Only!"
author = "gabehxd"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "270b7d3a51984e4f1d9e59aef885fddf60ca22786deba0ea8e131f73028b329f"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
