name = "Cool People Only!"
author = "gabehxd"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "258cbee694169f6bb89d981410d22f1262ab6feccc6c1a443006fce15d58415c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
